In [2]:
# Consider the below code to answer further questions:
import numpy as np
list_ = ['1' ,'2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
# QUESTION.1 Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#            to print the data types of both the variables.
# ANSWER import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", array_list.dtype)

Data type of list_: <class 'list'>
Data type of array_list: <U1


In [3]:
# QUESTION.2 Write a code to print the data type of each and every element of both the variables list_ and arra_list.
# ANSWER 
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of elements in list_
print("Data types of elements in list_:")
for i in list_:
    print(type(i))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for i in array_list:
    print(i.dtype)


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<U1
<U1
<U1
<U1
<U1


In [4]:
# QUESTION.3 Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.
# ANSWER 
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Data types of each element in list_
for i in list_:
    print("Data type of element in list_: ", type(i))

# Data types of each element in array_list
for i in array_list:
    print("Data type of element in array_list: ", type(i))


Data type of element in list_:  <class 'str'>
Data type of element in list_:  <class 'str'>
Data type of element in list_:  <class 'str'>
Data type of element in list_:  <class 'str'>
Data type of element in list_:  <class 'str'>
Data type of element in array_list:  <class 'numpy.int64'>
Data type of element in array_list:  <class 'numpy.int64'>
Data type of element in array_list:  <class 'numpy.int64'>
Data type of element in array_list:  <class 'numpy.int64'>
Data type of element in array_list:  <class 'numpy.int64'>


In [1]:
#  Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
# QUESTION.4 Write a code to find the following characteristics of variable, num_array:
#         (i) shape
#         (ii) size
# ANSWER 
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Finding the shape
shape = num_array.shape

# (ii) Finding the size
size = num_array.size

print("Shape:", shape)
print("Size:", size)


Shape: (2, 3)
Size: 6


In [2]:
# QUESTION.5 Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
#            creation function.
#           [Hint: The size of the array will be 9 and the shape will be (3,3).]
# ANSWER 
import numpy as np
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# QUESTION.6 Create an identity matrix of shape (5,5) using numpy functions?
#          [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
# ANSWER 
import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
